inflow_exclusion_list = [
    "RecurringSellRand",
    "SingleSellRand",
    "SingleSellUnit",
]

outflow_exclusion_list = [
    "SingleCashBuy",
]

final_exclude = [
    "InternalTransfer",
    "Opening Balance",
    "UnpaidDeposit",
    "PhaseOut",
]

check_list = [
    "PhaseOut",
    "PhaseOutBuy",
]

tmp_include = [
    "Opening Balance",
    "PhaseOut",
    "PhaseOutADF",
    "PhaseOutBuy",
    "RMBMergerTransfer",
    "RecurringDeposit",
    "RecurringElectronicBuy",
    "RecurringMoneyMarketWithdrawal",
    "RecurringSellRand",
    "RecurringSellUnit",
    "RecurringSellWithdrawal",
    "SellForFeesContractDepleted",
    "SellForInternalSwitch",
    "SellForPerformanceFeeRands",
    "SellForPerformanceFeeUnits",
    "SingleCapacityBuy",
    "SingleCashBuy",
    "SingleCashDeposit",
    "SingleCashDepositCompulsory",
    "SingleCashDepositVoluntary",
    "SingleElectronicBuy",
    "SingleElectronicDeposit",
    "SingleExternalSwitchSellUnit",
    "SingleMoneyMarketWithdrawal",
    "SingleSellApprovedFundTransferSection14Withdrawal",
    "SingleSellApprovedFundTransferSection372Withdrawal",
    "SingleSellBuy",
    "SingleSellCommutationOfAnnuity",
    "SingleSellDeathClaimWithdrawal",
    "SingleSellLoanWithdrawal",
    "SingleSellProvidentFundTransferSection14Withdrawal",
    "SingleSellRand",
    "SingleSellResignationWithdrawal",
    "SingleSellRetirementWithdrawal",
    "SingleSellSurrenderWithdrawal",
    "SingleSellTransferToInsurerWithdrawal",
    "SingleSellUnit",
    "UnpaidDepositRecurring",
    "UnrealisedRecurringSellWithdrawal",
    "VoluntaryWithdrawal",
    "WithdrawalForPerformanceFee",
    "WithdrawalUnrealisedPayment",
    "WithdrawalUnrealisedRecurringPayment",
    "WithdrawalUnrealisedSinglePayment",
    "YieldAdjustment",
    "BuyForInternalSwitch",
    "CapacityOffshorePhasingMoneyMarketWithdrawal",
    "TransferOfOwnership",
    "BuyForInternalSwitch",
    "SellForInternalSwitch",
]

tmp_exclude = [
    'BuyFromShareRoundingForFees',
    'InternalTransfer',
    'SellForFees',
    "SellForCGT",
    'BuyFromShareRoundingForOffshoreDividends',
    'BuyFromShareRoundingForInterest',
    'BuyFromShareRoundingForOffshoreInterest',
    'BuyFromShareRoundingForDividends',
    'AdjustmentServiceFeeFromFeeEngine',
    'BuyFromShareRoundingForBuy',
    'CorrectionInitialCommissionFromFeeEngine',
    'AdditionalGrowthAmountAfterDirective',
    "ServiceFeeFromFeeEngine",
    "AdjustmentAdvisoryFee",
    "AdjustmentAdvisoryFeeVAT",
    "AdjustmentBuy",
    "AdjustmentDeposit",
    "AdjustmentExternalTransfer",
    "AdjustmentIncomeTax",
    "AdjustmentInitialFee",
    "AdjustmentInterest",
    "AdjustmentInterestOnLateAllocation",
    "AdjustmentManagementFee",
    "AdjustmentManagementFeeVAT",
    "AdjustmentRecurringSellWithdrawal",
    "AdjustmentSell",
    "AdjustmentSellPSPAdditionalCash",
    "AdjustmentSwitchFeeCash",
    "AdjustmentTaxOnRIO",
    "AdjustmentVoluntaryRAContributionTransfer",
    "AdjustmentWithdrawal",
    "AdjustmentWrongPriceSell",
    "AdvisoryFee",
    "AdvisoryFeeCash",
    "AdvisoryFeeCashAccount",
    "AdvisoryFeeFromFeeEngine",
    "AdvisoryFeeInternalSwitch",
    "AdvisoryFeeUnitTrust",
    "AdvisoryFeeVAT",
    "AdvisoryFeeVATCash",
    "AdvisoryFeeVATCashAccount",
    "AdvisoryFeeVATInternalSwitch",
    "AdvisoryFeeVATUnitTrust",
    "CapacityFee",
    "CapitalGainTaxDeduction",
    "CapitalGainTaxDeductionInCash",
    "CapitalGainTaxDeductionInternalSwitch",
    "ContractConsolidation",
    "CorporateAction - ABIL",
    "CorrectionAdvisoryFeeFromFeeEngine",
    "CurrencyTransfer",
    "CurrencyTransferExternalSwitch",
    "DividendTaxWithheldDualListed",
    "DividendTaxWithheldOffshore",
    "DividendWithholdingTax",
    "DividendsDeclared",
    "DividendsDeclaredCashDWTApplicable",
    "DividendsDeclaredCashDWTNotApplicable",
    "DividendsDeclaredDualListedDWTApplicable",
    "DividendsDeclaredDualListedDWTNotApplicable",
    "DividendsDeclaredInSpecie",
    "DividendsDeclaredREITDWTNotApplicable",
    "DividendsReinvested",
    # "ExternalTransfer",
    # "ExternalTransferIn",
    # "ExternalTransferOut",
    "ITA88Deduction",
    "ImmediatePaymentFee",
    "IncomeTax",
    "InitialCommission",
    "InitialCommissionFromFeeEngine",
    "InitialCommissionVAT",
    "InitialFee",
    "InitialFeeVAT",
    "InitialFundManagerFee",
    "InitialFundManagerFeeDividends",
    "InitialFundManagerFeeInterest",
    "InitialFundManagerFeeOffshoreDividends",
    "InitialFundManagerFeeOffshoreInterest",
    "Interest",
    "InterestDeclared",
    "InterestDeclaredSubjectToSAWithholdingTax",
    "InterestDeclaredSubjectToSAWithholdingTaxWTINotApplicable",
    "InterestOnLateAllocation",
    "InterestReinvested",
    "InterestSubjectToSAWithholdingTax",
    "InterestSubjectToSAWithholdingTaxWTINotApplicable",
    "InterestTaxWithheldOffshore",
    "ManagementFee",
    "ManagementFeeCash",
    "ManagementFeeCashAccount",
    "ManagementFeeInternalSwitch",
    "ManagementFeeUnitTrust",
    "ManagementFeeVAT",
    "ManagementFeeVATCash",
    "ManagementFeeVATUnitTrust",
    "OffshoreDividendsDeclared",
    "OffshoreDividendsReinvested",
    "OffshoreInterestDeclared",
    "OffshoreInterestReinvested",
    "OffshoreMergerTransfer",
    "OffshoreSystemConversion",
    "PriceCorrection",
    "ProfitOrLossAdminErrorAdjustment",
    "RetirementFundTax",
    "RetirementFundTaxForInterestOnLateAllocation",
    "RoundingAdjustment",
    "SwitchFeeCash",
    "SwitchFeeInternalSwitch",
    "SwitchFeeVATCash",
    # "SwitchUnit",
    "TaxFreeExcessCashTransfer",
    "TaxOnInterest",
    "TaxOnInterestForInterestOnLateAllocation",
    "TaxOnRIO",
    "TaxOnRIOUnrealisedPayment",
    # "TransferDeathClaim",
    "TransferForCorrection",
    # "TransferOfCompulsoryDeathPortion",
    # "TransferOfCompulsoryRetirementPortion",
    "UnpaidInitialCommission",
    "UnpaidInitialCommissionVAT",
]

start_list = [
    "AdjustmentInterest",
    "AdjustmentSell",
    "AdjustmentSellPSPAdditionalCash",
    "AdjustmentVoluntaryRAContributionTransfer",
    "AdvisoryFeeFromFeeEngine",
    "BuyForInternalSwitch",
    "CapitalGainTaxDeduction",
    "CapitalGainTaxDeductionInCash",
    "ContractConsolidation",
    "CorrectionAdvisoryFeeFromFeeEngine",
    "CurrencyTransfer",
    "DividendTaxWithheldDualListed",
    "DividendTaxWithheldOffshore",
    "DividendWithholdingTax",
    "DividendsDeclaredCashDWTApplicable",
    "DividendsDeclaredCashDWTNotApplicable",
    "DividendsDeclaredDualListedDWTApplicable",
    "DividendsDeclaredDualListedDWTNotApplicable",
    "DividendsDeclaredInSpecie",
    "DividendsDeclaredREITDWTNotApplicable",
    "DividendsReinvested",
    "IncomeTax",
    "InitialCommissionFromFeeEngine",
    "Interest",
    "InterestDeclared",
    "InterestDeclaredSubjectToSAWithholdingTaxWTINotApplicable",
    "InterestOnLateAllocation",
    "InterestReinvested",
    "InterestTaxWithheldOffshore",
    "ManagementFee",
    "ManagementFeeUnitTrust",
    "OffshoreDividendsDeclared",
    "OffshoreDividendsReinvested",
    "OffshoreInterestDeclared",
    "OffshoreInterestReinvested",
    "PhaseOutADF",
    "PhaseOutBuy",
    "RecurringMoneyMarketWithdrawal",
    "RecurringSellRand",
    "RecurringSellWithdrawal",
    "SellForCGT",
    "SellForFeesContractDepleted",
    "SellForInternalSwitch",
    "ServiceFeeContractDepleted",
    "ServiceFeeFromFeeEngine",
    "SingleCashBuy",
    "SingleCashDeposit",
    "SingleCashDepositCompulsory",
    "SingleCashDepositVoluntary",
    "SingleExternalSwitchSellUnit",
    "SingleMoneyMarketWithdrawal",
    "SingleSellApprovedFundTransferSection14Withdrawal",
    "SingleSellBuy",
    "SingleSellDeathClaimWithdrawal",
    "SingleSellLoanWithdrawal",
    "SingleSellRand",
    "SingleSellResignationWithdrawal",
    "SingleSellTransferToInsurerWithdrawal",
    "SingleSellUnit",
    "SwitchUnit",
    "TaxFreeExcessCashTransfer",
    "TaxOnInterest",
    "TaxOnInterestForInterestOnLateAllocation",
    "TaxOnRIO",
    "UnpaidDeposit",
    "UnrealisedRecurringSellWithdrawal",
    "VoluntaryWithdrawal",
    "WithdrawalUnrealisedRecurringPayment",
]

search_list = [
    "SwitchUnit",
    "RecurringDeposit",
    "RecurringElectronicBuy",
    "RecurringMoneyMarketWithdrawal",
    "RecurringSellRand",
    "RecurringSellUnit",
    "RecurringSellWithdrawal",
    "ExternalTransfer",
    "ExternalTransferIn",
    "ExternalTransferOut",
    "SingleCashDepositVoluntary",
    "CurrencyTransfer",
    "VoluntaryWithdrawal",
    "SingleMoneyMarketWithdrawal",
    "RecurringSellRand",
    "RecurringMoneyMarketWithdrawal",
    "RecurringSellWithdrawal",
    "SingleCashDeposit",
    "SingleSellBuy",
    "SellForInternalSwitch",
    "SingleSellRand",
    "SingleSellUnit",
    "SingleCashBuy",
    "SingleCashDeposit",
    "SingleCashDepositCompulsory",
    "SingleCashDepositVoluntary",
    "SingleElectronicBuy",
    "SingleElectronicDeposit",
    "SingleExternalSwitchSellUnit",
    "SingleMoneyMarketWithdrawal",
    "SingleSellApprovedFundTransferSection14Withdrawal",
    "SingleSellApprovedFundTransferSection372Withdrawal",
    "SingleSellBuy",
    "SingleSellCommutationOfAnnuity",
    "SingleSellDeathClaimWithdrawal",
    "SingleSellLoanWithdrawal",
    "SingleSellProvidentFundTransferSection14Withdrawal",
    "SingleSellRand",
    "SingleSellResignationWithdrawal",
    "SingleSellRetirementWithdrawal",
    "SingleSellSurrenderWithdrawal",
    "SingleSellTransferToInsurerWithdrawal",
    "SingleSellUnit",
    "SingleSellUnit",
    "SingleSellUnit",
]

unique_list = ['RecurringSellWithdrawal', 'SellForCGT',
               'RecurringMoneyMarketWithdrawal', 'SingleSellRand',
               'SingleSellBuy', 'SingleSellUnit', 'RecurringSellRand',
               'VoluntaryWithdrawal', 'SwitchUnit', 'BuyFromShareRoundingForFees',
               'SingleMoneyMarketWithdrawal',
               'SingleSellApprovedFundTransferSection372Withdrawal',
               'BuyForInternalSwitch', 'SellForInternalSwitch', 'SellForFees',
               'SingleCashBuy', 'UnrealisedVoluntaryWithdrawal',
               'SingleCashDepositVoluntary',
               'TaxFreeWithdrawalToApprovedProvider',
               'TransferToInsurerExternalTransferOut',
               'SellForFeesContractDepleted',
               'TransferToApprovedFundSection14ExternalTransferOut',
               'InternalTransfer', 'TransferOfCompulsoryDeathPortion',
               'WithdrawalUnrealisedSinglePayment', 'SingleElectronicBuy',
               'SingleElectronicDeposit',
               'CorrectionInitialCommissionFromFeeEngine',
               'SingleSellApprovedFundTransferSection14Withdrawal',
               'AdditionalGrowthAmountAfterDirective', 'RecurringSellUnit',
               'SingleCashDepositCompulsory', 'SingleCashDeposit',
               'WithdrawalUnrealisedRecurringPayment', 'PhaseOutADF',
               'UnrealisedRecurringSellWithdrawal', 'TransferOfOwnership',
               'PhaseOutBuy',
               'SingleSellApprovedFundTransferDeathClaimWithdrawal',
               'SingleSellDeathClaimWithdrawal',
               'BuyFromShareRoundingForOffshoreDividends',
               'BuyFromShareRoundingForInterest',
               'BuyFromShareRoundingForOffshoreInterest',
               'BuyFromShareRoundingForDividends',
               'AdjustmentServiceFeeFromFeeEngine', 'RecurringElectronicBuy',
               'RecurringDeposit', 'SingleSellTransferToInsurerWithdrawal',
               'BuyFromShareRoundingForBuy',
               'TransferVoluntaryExternalTransferOut']
